"""
Zack.ai — Config Loader (Commenting Agent)
===========================================
Reads your personalised zack_config.py automatically.
All Zack scripts import this instead of hardcoding values.
"""

import os

try:
    import zack_config as cfg
    CONFIG_LOADED = True
except ImportError:
    CONFIG_LOADED = False
    cfg = None


def get(key, default=""):
    if cfg and hasattr(cfg, key):
        return getattr(cfg, key)
    return os.environ.get(key, default)


# ── Core credentials ──────────────────────────────────────────────────────────
SPREADSHEET_ID          = get("SPREADSHEET_ID")
GOOGLE_CREDENTIALS_PATH = get("GOOGLE_CREDENTIALS_PATH", "google_credentials.json")
GROQ_API_KEY            = get("GROQ_API_KEY")

# ── Identity ──────────────────────────────────────────────────────────────────
CLIENT_NAME             = get("CLIENT_NAME",       "Zack User")
CLIENT_FIRST_NAME       = get("CLIENT_FIRST_NAME", "")
CLIENT_TITLE            = get("CLIENT_TITLE",      "Founder")
CLIENT_COMPANY          = get("CLIENT_COMPANY",    "")
CLIENT_LINKEDIN         = get("CLIENT_LINKEDIN",   "")

# ── Sheet ─────────────────────────────────────────────────────────────────────
SHEET_ENGAGEMENT        = get("SHEET_ENGAGEMENT", "Zacharia Engagement List")

# ── Commenting settings ───────────────────────────────────────────────────────
MAX_COMMENTS_PER_RUN    = int(get("MAX_COMMENTS_PER_RUN", 25))
POST_RECENCY_HOURS      = int(get("POST_RECENCY_HOURS",   72))

# ── Voice profile ─────────────────────────────────────────────────────────────
# This comes from the user's personalised zack_config.py generated by zack_setup.py
COMMENTING_PLAYBOOK     = get("COMMENTING_PLAYBOOK", "")


if not CONFIG_LOADED:
    print("⚠️  zack_config.py not found in this folder.")
    print("   Run: python zack_setup.py")
    print("   This creates your personalised config file.")
